"use client";

import Header from "@/components/common/Header";
import "./globals.css";
import Footer from "@/components/common/Footer";
import { usePathname } from "next/navigation";
import Providers from "./providers";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  // Header/Footer를 숨길 경로들
  const hiddenPaths = ["/login", "/signup"];
  const isHidden = hiddenPaths.some((path) => pathname.startsWith(path));

  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen">
          <Providers>
            {!isHidden && <Header />}
            <main className="flex-1">{children}</main>
            {!isHidden && <Footer />}
          </Providers>
        </div>
      </body>
    </html>
  );
}
